### ISSUE TITLE
Сломалась авторизация

### ISSUE THREAD

**Issue by Ka3e1** [VKUnicorn/VK-Unicorn#3]
Ошибка: не удалось авторизироваться. Причина: Неверный логин или пароль.

**Comment by AlexEnse** [comment]
Да, есть такое, но можно легко поправить пока не зальют коммит

Поднимаем NetFramework до 4.7.2
Обновляем в менеджере пакетов Nuget до последней версии VK NET

И заменяем авторизацию при помощи расширения https://github.com/shelln1ght/VkNet.AudioBypass

Добавляйте его через менеджер пакетов и переписывайте метод PrepareVkApi в файле Worker.cs

```
        void PrepareVkApi()
        {
            var services = new ServiceCollection();
            services.AddAudioBypass();

            api = new VkApi(services);
            api.OnTokenExpires += (sender) =>
            {
                isAuthorized = false;

                Utils.Log("Токен авторизации стал недействительным. Будет необходимо авторизироваться заново", LogLevel.WARNING);
            };
        }
```
В этом же файле еще нужны завистимости

```
using VkNet.AudioBypassService.Extensions;
using Microsoft.Extensions.DependencyInjection;
```

Завелось :)

**Comment by Ka3e1** [comment]
А можно форк с фиксом?

**Comment by VKUnicorn** [comment]
Извиняюсь за задержку. Коммитнул исправленную версию, распространите на бордах пожалуйста сами, времени совсем нет. Спасибо за поддержку и донаты.
